version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # AMQP
      - 15672:15672 # Management UI

  postgres:
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_resize_system

